[package]
name = "simple_webcam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rscam = "0.5.5"
image = "0.23.14"
imageproc = "0.22.0"
show-image = {version = "0.14.0", features = ["image"]}